### ISSUE TITLE
New Installation: "Warning: preg_replace(): Compilation failed: invalid range in character class at offset 16 in [...] /Wakka.class.php on line 2041"

### ISSUE THREAD

**Issue by markcsg** [wikkawik/WikkaWiki#1211]
A new installation immediately and repeatedly gives multiple errors with every page as follows:

> Warning: preg_replace(): Compilation failed: invalid range in character class at offset 16 in /home/synaptaorg/public_html/wikka/libs/Wakka.class.php on line 2041

**System Info:**

![sysinfo](https://cloud.githubusercontent.com/assets/12546112/13855558/ee1476c2-ec68-11e5-908c-14ea823e9213.png)

**Screenshot examples:**

![home page errors](https://cloud.githubusercontent.com/assets/12546112/13855497/acde98c2-ec68-11e5-9d53-7d904b54e6e9.png)

![categories](https://cloud.githubusercontent.com/assets/12546112/13855747/c0d00dba-ec69-11e5-8300-755ebfb846e8.png)

The installation has been wiped and attempted three times, each with identical results.

Cursory examination of the file Wakka.class.php does not reveal to me an obvious cause for the exception. However, I am not a programmer.

**Comment by klenwell** [comment]
Looks like a problematic regex pattern is being passed to the [CleanTextNode](https://github.com/wikkawik/WikkaWiki/blob/1.3.6/libs/Wakka.class.php#L2013) function.

The function provides a default parameter `/[^A-Za-z0-9_:.-\s]/`. Offset 16 would be the last dash `-` there, which looks like it could perhaps use an escape character `\` in front of it.

The same problem appears to be identified in this Stack Overflow question:

http://stackoverflow.com/questions/27426645/preg-match-compilation-failed-invalid-range

I cannot reproduce the problem on my system (PHP 5.5.28-1+deb.sury.org~precise+1 (cli)).

@markcsg, can you copy the following small script into a file and run it on your system to see if it reproduces the error:

    <?php
    
    $p1 = '/[^A-Za-z0-9_:.-\s]/';
    $input = 'abc?def';
    echo preg_replace($p1, '', $input);
    
To run from command line:

    php -f your-file.php

I suspect the problem is cause by a change in the regex defaults with newer versions of PHP. If so, one fix would be to change the default value for `$pattern_prohibited_chars` in line 2013 from `/[^A-Za-z0-9_:.-\s]/` to `/[^A-Za-z0-9_:.\-\s]/` (i.e., escape the last dash). I'd feel more confident, however, if I were able to reproduce the issue first.

**Comment by markcsg** [comment]
Yes, I'd spotted the problem being previously identified as associated with changes to PHP version and the minus / dash character. I couldn't easily see where the error was arising from though.

I'll try running the script and possibly try the change to the `$pattern_prohibited_chars` default value in line 2013.

**Comment by klenwell** [comment]
I was able to find an online PHP sandbox that offers different versions of PHP and reproduce the problem using **PHP 5.5.31**.

Here is the original regex pattern `/[^A-Za-z0-9_:.-\s]/` that reproduces the issue (click `Execute code` button to see result):

http://sandbox.onlinephpfunctions.com/code/2497852196b96149e7d174b2a94a5b4066d748cc

Here is the code with the fixed pattern `/[^A-Za-z0-9_:.\-\s]/`:

http://sandbox.onlinephpfunctions.com/code/ed957b8a4ce365f35420edf43ed6373cb054cbf7

@markcsg if you can make that change in the source, it should get rid of those warnings.

I'll mark this issue a bug. The default parameter value should be fixed for compatibility with newer versions of PHP.

**Comment by markcsg** [comment]
Many thanks, I'll make the change.
Much appreciated.

**Comment by markcsg** [comment]
Amending the source file has fixed the issue.

**Comment by bakoontz** [comment]
Glad you got it working (thanks klenwell). This is a dupe of #1181, which is a nice reminder for me to get 1.3.7 out the door.
