### ISSUE TITLE
Add [New page] menulet in footer

### ISSUE THREAD

**Issue by bakoontz** [wikkawik/WikkaWiki#1249]
Working with some of my students, it has become obvious that new page creation isn't exactly intuitive.  We need to add a [New page] menulet on the footer of each page to make things obvious.

**Comment by klenwell** [comment]
That's great that your students are using WikkaWiki and providing feedback.

:+1: on the change. I suppose for experienced wiki users, the new page button is a bit of a [placebo button](https://en.wikipedia.org/wiki/Placebo_button), since you're usually adding pages as links from existing pages. But I can see the importance for new users.

Ultimately, maybe there could be a user-defined option that toggles between an UI for new and experienced users. It could be a fun UX exercise for a frontend specialist.
